height = input("enter your height in m: ")
weight = input("enter your weight in kg: ")
float_height = float(height)
float_weight = float(weight)
BMI = float_weight / (float_height ** 2)
print(int(BMI))